import os
from utils import db
from utils.utils import DIR, data

SCHEMA = data["DB"]["SCHEMA"]

def on_ready():
    if not os.path.isdir(f"{DIR}/data"):
        os.mkdir(f"{DIR}/data")
    if not os.path.isdir(f"{DIR}/data/extensions"):
        os.mkdir(f"{DIR}/data/extensions")
    if not os.path.isdir(f"{DIR}/extensions"):
        os.mkdir(f"{DIR}/extensions")

    db.cursor.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA};")

    # user table
    db.cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS {SCHEMA}.user_perms (
            server_id BIGINT NOT NULL,
            user_id BIGINT NOT NULL,
            perms JSONB,
            PRIMARY KEY (server_id, user_id)
        );
    """)

    db.cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS {SCHEMA}.user_data (
            user_id BIGINT PRIMARY KEY,
            data JSONB
        );
    """)

    db.cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS {SCHEMA}.server_perms (
            server_id BIGINT PRIMARY KEY,
            perms JSONB
        );
    """)

    db.cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS {SCHEMA}.role (
            server_id BIGINT NOT NULL,
            role_id BIGINT NOT NULL,
            perms JSONB,
            PRIMARY KEY (server_id, role_id)
        );
    """)

    # message history table
    db.cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS {SCHEMA}.history (
            message BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reply BIGINT,
        );
    """)
    
    db.logger._logger.info("Defined Schema and Tables")

on_ready()
