import os
from utils import db
from utils.utils import DIR

def on_ready():
    if not os.path.isdir(f"{DIR}/data"):
        os.mkdir(f"{DIR}/data")
    if not os.path.isdir(f"{DIR}/data/users"):
        os.mkdir(f"{DIR}/data/users")
    if not os.path.isdir(f"{DIR}/data/history"):
        os.mkdir(f"{DIR}/data/history")
    if not os.path.isdir(f"{DIR}/data/extensions"):
        os.mkdir(f"{DIR}/data/extensions")
    if not os.path.isdir(f"{DIR}/extensions"):
        os.mkdir(f"{DIR}/extensions")
    if not os.path.isdir(f"{DIR}/data/roles"):
        os.mkdir(f"{DIR}/data/roles")

    db.cursor.execute("CREATE SCHEMA IF NOT EXISTS sonny;")

    # user table
    db.cursor.execute("""
        CREATE TABLE IF NOT EXISTS sonny.user (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            perms JSONB,
            data JSONB
        );
    """)

    db.cursor.execute("""
        CREATE TABLE IF NOT EXISTS sonny.role (\
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            perms JSONB
        );
    """)

    # message history table
    db.cursor.execute("""
        CREATE TABLE IF NOT EXISTS sonny.history (\
            message BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reply BIGINT
        );
    """)
    
    print("Schema and Tables defined successfully!")

on_ready()
