from typing import Literal
from utils import db
from api import _ext

def table(name: str, custom_serial: bool, columns: dict[str, Literal["SMALLINT", "INT", "BIGINT",
                                                "NUMERIC", "TEXT", "BOOLEAN",
                                                "DOUBLE PRECISION", "SERIAL",
                                                "BIGSERIAL", "TEXT", "JSONB",
                                                "TIMESTAMP", "TIMESTAMPTZ",
                                                "DATE", "TIME", "INTERVAL"]]):
    """
    Create a table
    """
    if ":" in name:
        name = name.replace(":", "$")
    if "$" not in name:
        name = f"{_ext()}${name}"
    if custom_serial:
        k, v =next(iter(columns.items()))
        columns[k] = f"{v} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    db.run(f"CREATE TABLE IF NOT EXISTS {name} ({', '.join([f'{k} {v}' for k, v in columns.items()])});")
        
def table_info(name: str) -> list[tuple[str, str]]:
    """
    Get table column names and data types
    """
    return db.query(f"""
                    SELECT column_name, data_type
                    FROM information_schema.columns
                    WHERE table_schema = 'sonny'
                    AND table_name = '{name}'
                    ORDER BY ordinal_position;
                    """)

def run(*args):
    db.run(*args)

def insert(table: str, columns: tuple[str], values: tuple):
    db.insert(table, columns, values)

def insert_exclusive(table: str, columns: tuple[str], values: tuple):
    db.insert_exclusive(table, columns, values)

def get(table: str, key: str, value: str) -> tuple:
    return db.get(table, value, key)

def delete(table: str, key: str, value: str):
    db.delete(table, key, value)